name = "Chemostat_Heerden2013"
uuid = "8fa5c008-a42b-11ea-347c-a57b2769cfbc"
authors = ["josePereiro"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
